name: Build and deploy Laravel app to Azure Web App - Olivia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_pgsql
          tools: composer

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build frontend assets
        run: |
          npm ci
          npm run build

      - name: Prepare files for deployment
        run: |
          mkdir -p public
          cp -r app bootstrap config database resources routes storage artisan composer.* public/
          [ -d lang ] && cp -r lang public/lang || true
          [ -d vendor ] && cp -r vendor public/vendor || true
          [ -f .env ] && cp .env public/.env || true
          [ -f public/.htaccess ] && cp public/.htaccess public/.htaccess || true
          shell: /usr/bin/bash -e {0}
          env:
            COMPOSER_PROCESS_TIMEOUT: 0
            COMPOSER_NO_INTERACTION: 1
            COMPOSER_NO_AUDIT: 1


      - name: Zip artifact for deployment
        run: |
          cd public
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B85A77D2B444A58AB015897644C7D57 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FFC7F5363D2740CD865FF0C3BBE620EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A54DED14A8064FB6ABAD6AEF714913BB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Olivia'
          slot-name: 'Production'
          package: .
