name: Build and deploy Laravel app to Azure Web App - Olivia
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_pgsql
          tools: composer
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install and build frontend assets
        run: |
           echo "APP_URL=https://olivia-g4htendadecwc7fu.canadacentral-01.azurewebsites.net" >> .env
           echo "ASSET_URL=https://olivia-g4htendadecwc7fu.canadacentral-01.azurewebsites.net" >> .env
           npm ci
           npm run build

      - name: Build Vite assets
        env:
          VITE_APP_URL: ${{ secrets.APP_URL }}
        run: npm run build
      - name: Prepare files for deployment
        run: |
          mkdir -p deploy
          cp -r public/* deploy/
          cp -r public/build deploy/build
          cp -r vendor deploy/vendor
          cp -r bootstrap deploy/bootstrap
          cp -r storage deploy/storage
          cp -r resources deploy/resources
          cp artisan deploy/artisan
          cp vite.config.js deploy/vite.config.js
          cp .env deploy/.env || true
          cp web.config deploy/web.config
      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../release.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

      - name: Cache Laravel config & routes
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan filament:optimize

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app
      - name: Unzip artifact
        run: unzip release.zip -d .
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B85A77D2B444A58AB015897644C7D57 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FFC7F5363D2740CD865FF0C3BBE620EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A54DED14A8064FB6ABAD6AEF714913BB }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Olivia'
          slot-name: 'Production'
          package: .
